preprocessing:
  target_column: Potability
  feature_columns: null
  test_size: 0.15
  random_state: 73
  shuffle: true
  stratify: true
  zscore_threshold: 3.0
  rfe:
    enabled: true
    step: 1
    cv_folds: 10
    scoring: roc_auc
    n_jobs: -1
    logistic_max_iter: 5000
    random_state: 73

modeling:
  cross_validation:
    n_splits: 5
    shuffle: true
    random_state: 73

  logistic_regression:
    max_iter: 1000
    solver: lbfgs
    random_state: 73

  random_forest:
    n_estimators: 300
    max_depth: null
    min_samples_leaf: 1
    min_samples_split: 2
    max_features: sqrt
    bootstrap: true
    class_weight: null
    criterion: gini
    max_samples: null
    random_state: 73
    n_jobs: -1

  random_forest_optimization:
    enabled: true
    n_trials: 75
    sampler: tpe
    random_state: 73
    objective_metric: f1

    search_space:
      n_estimators:
        type: int
        low: 300
        high: 1000
        step: 100

      max_depth:
        type: categorical
        choices: [5, 10, 15, 20, 30, 50, null]

      min_samples_leaf:
        type: int
        low: 1
        high: 20

      min_samples_split:
        type: int
        low: 2
        high: 40

      max_features:
        type: categorical
        choices: [sqrt, log2, 0.3, 0.5, 0.7, null]

      bootstrap:
        type: categorical
        choices: [true]

      class_weight:
        type: categorical
        choices: [null, balanced, balanced_subsample]

      criterion:
        type: categorical
        choices: [gini, entropy, log_loss]

      max_samples:
        type: float
        low: 0.6
        high: 1.0

  mlflow:
    tracking_uri: mlruns
    experiment_name: water_potability_modeling
    run_name: logistic_regression_baseline
    random_forest_run_name: random_forest_nonlinear_probe
